NAME: CenterFusionBaseline
CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
GPUS:
- 0
- 1
- 2
WORKERS: 6
DEBUG: 0
EVAL: false
RANDOM_SEED: 0
MIXED_PRECISION: true
CONF_THRESH: 0.3

DATASET:
  DATASET: 'nuscenes'
  ROOT: data/
  RANDOM_CROP: false
  MAX_CROP: true
  SHIFT: 0.2
  SCALE: 0
  ROTATE: 0
  FLIP: 0.5
  COLOR_AUG: true
  TRAIN_SPLIT: 'train'
  VAL_SPLIT: 'val'
  NUSCENES:
    RADAR_PC: false
    MAX_PC: 1000
    MAX_PC_DIST: 60.0
    PC_Z_OFFSET: 0.0
    PC_ROI_METHOD: 'pillars'
    PILLAR_DIMS: (1.5, 0.2, 0.2)

MODEL:
  LOAD_DIR: 'models/nuScenes_3Ddetection_e140.pth'
  ARCH: "dla_34"
  FREEZE_BACKBONE: true
  FUSION_STRATEGY: 'middle' # TODO
  INPUT_SIZE: (448, 800)
  FRUSTUM: true
  K: 100
  GENERIC_NET:
    BACKBONE: "dla34"
    NECK: "dlaup"
  DLA:
    NODE: "DeformConv"

LOSS:
  NUSCENES_ATT: false
  VELOCITY: true
  WEIGHTS:
    HEATMAP: 1
    AMODAL_OFFSET: 1
    BBOX: 0.1
    DEPTH: 1
    DIMENSION: 1
    ROTATION: 1
    NUSCENES_ATT: 1
    VELOCITY: 1

TRAIN:
  BATCH_SIZE: 128
  SHUFFLE: true
  EPOCHS: 170
  RESUME: true
  OPTIMIZER: adam
  LR: 2.5e-4
  LR_STEP: (220,)
  SAVE_INTERVALS: 10
  VAL_INTERVALS: 5
  SCALE_FACTOR: 16

TEST:
  BATCH_SIZE: 256
  OFFICIAL_EVAL: true
